package io.github.ac1982.tcec.protocol;
import io.github.ac1982.tcec.model.*;
import java.util.List;
/** Typed charging, parking, ground-lock and H5 endpoints in a single registry. */
public final class Endpoints {
    private Endpoints() {}
    public static final Endpoint<QueryTokenRequest, QueryTokenResponse> QUERY_TOKEN = new Endpoint<>("query_token", QueryTokenRequest.class, QueryTokenResponse.class, false, "/evcs/sdk/query_token");
    public static final Endpoint<QueryStationsInfoRequest, QueryStationsInfoResponse> QUERY_STATIONS_INFO = new Endpoint<>("query_stations_info", QueryStationsInfoRequest.class, QueryStationsInfoResponse.class, true, "/evcs/v1/query_stations_info");
    public static final Endpoint<NotificationStationStatusRequest, NotificationStationStatusResponse> NOTIFICATION_STATION_STATUS = new Endpoint<>("notification_stationStatus", NotificationStationStatusRequest.class, NotificationStationStatusResponse.class, true, "/notification_stationStatus");
    public static final Endpoint<QueryStationStatusRequest, QueryStationStatusResponse> QUERY_STATION_STATUS = new Endpoint<>("query_station_status", QueryStationStatusRequest.class, QueryStationStatusResponse.class, true, "/evcs/v1/query_station_status");
    public static final Endpoint<QueryStationStatsRequest, QueryStationStatsResponse> QUERY_STATION_STATS = new Endpoint<>("query_station_stats", QueryStationStatsRequest.class, QueryStationStatsResponse.class, true, "/evcs/v1/query_station_stats");
    public static final Endpoint<QueryEquipAuthRequest, QueryEquipAuthResponse> QUERY_EQUIP_AUTH = new Endpoint<>("query_equip_auth", QueryEquipAuthRequest.class, QueryEquipAuthResponse.class, true, "/evcs/v1/query_equip_auth");
    public static final Endpoint<QueryEquipBusinessPolicyRequest, QueryEquipBusinessPolicyResponse> QUERY_EQUIP_BUSINESS_POLICY = new Endpoint<>("query_equip_business_policy", QueryEquipBusinessPolicyRequest.class, QueryEquipBusinessPolicyResponse.class, true, "/evcs/v1/query_equip_business_policy");
    public static final Endpoint<QueryStartChargeRequest, QueryStartChargeResponse> QUERY_START_CHARGE = new Endpoint<>("query_start_charge", QueryStartChargeRequest.class, QueryStartChargeResponse.class, true, "/evcs/v1/query_start_charge");
    public static final Endpoint<NotificationStartChargeResultRequest, NotificationStartChargeResultResponse> NOTIFICATION_START_CHARGE_RESULT = new Endpoint<>("notification_start_charge_result", NotificationStartChargeResultRequest.class, NotificationStartChargeResultResponse.class, true, "/notification_start_charge_result");
    public static final Endpoint<QueryEquipChargeStatusRequest, QueryEquipChargeStatusResponse> QUERY_EQUIP_CHARGE_STATUS = new Endpoint<>("query_equip_charge_status", QueryEquipChargeStatusRequest.class, QueryEquipChargeStatusResponse.class, true, "/evcs/v1/query_equip_charge_status");
    public static final Endpoint<ChargingSnapshot, NotificationEquipChargeStatusResponse> NOTIFICATION_EQUIP_CHARGE_STATUS = new Endpoint<>("notification_equip_charge_status", ChargingSnapshot.class, NotificationEquipChargeStatusResponse.class, true, "/notification_equip_charge_status");
    public static final Endpoint<QueryStopChargeRequest, QueryStopChargeResponse> QUERY_STOP_CHARGE = new Endpoint<>("query_stop_charge", QueryStopChargeRequest.class, QueryStopChargeResponse.class, true, "/evcs/v1/query_stop_charge");
    public static final Endpoint<NotificationStopChargeResultRequest, NotificationStopChargeResultResponse> NOTIFICATION_STOP_CHARGE_RESULT = new Endpoint<>("notification_stop_charge_result", NotificationStopChargeResultRequest.class, NotificationStopChargeResultResponse.class, true, "/notification_stop_charge_result");
    public static final Endpoint<ChargeOrderInfo, NotificationChargeOrderInfoResponse> NOTIFICATION_CHARGE_ORDER_INFO = new Endpoint<>("notification_charge_order_info", ChargeOrderInfo.class, NotificationChargeOrderInfoResponse.class, true, "/notification_charge_order_info");
    public static final Endpoint<CheckChargeOrdersRequest, CheckChargeOrdersResponse> CHECK_CHARGE_ORDERS = new Endpoint<>("check_charge_orders", CheckChargeOrdersRequest.class, CheckChargeOrdersResponse.class, true, "/check_charge_orders");
    public static final Endpoint<QueryOpenLinkRequest, QueryOpenLinkResponse> QUERY_OPEN_LINK = new Endpoint<>("query_open_link", QueryOpenLinkRequest.class, QueryOpenLinkResponse.class, true, "/evcs/v1/query_open_link");
    public static final Endpoint<QueryGroundLocksRequest, QueryGroundLocksResponse> QUERY_GROUND_LOCKS = new Endpoint<>("query_ground_locks", QueryGroundLocksRequest.class, QueryGroundLocksResponse.class, true, "/evcs/sdk/query_ground_locks");
    public static final Endpoint<QueryParkingFreeInfoRequest, QueryParkingFreeInfoResponse> QUERY_PARKING_FREE_INFO = new Endpoint<>("query_parking_free_info", QueryParkingFreeInfoRequest.class, QueryParkingFreeInfoResponse.class, true, "/evcs/v1/query_parking_free_info");
    public static final Endpoint<QueryConfirmLinkRequest, QueryConfirmLinkResponse> QUERY_CONFIRM_LINK = new Endpoint<>("query_confirm_link", QueryConfirmLinkRequest.class, QueryConfirmLinkResponse.class, true, "/evcs/v1/query_confirm_link");
    public static final Endpoint<NotificationUserAuthRequest, NotificationUserAuthResponse> NOTIFICATION_USER_AUTH = new Endpoint<>("notification_user_auth", NotificationUserAuthRequest.class, NotificationUserAuthResponse.class, true, "/notification_user_auth");
    public static final Endpoint<QueryParkingStationRequest, QueryParkingStationResponse> QUERY_PARKING_STATION = new Endpoint<>("query_parking_station", QueryParkingStationRequest.class, QueryParkingStationResponse.class, true, "/evcs/v1/query_parking_station");
    public static final Endpoint<QueryParkingFreeWaveRequest, QueryParkingFreeWaveResponse> QUERY_PARKING_FREE_WAVE = new Endpoint<>("query_parking_free_wave", QueryParkingFreeWaveRequest.class, QueryParkingFreeWaveResponse.class, true, "/evcs/v1/query_parking_free_wave");
    public static final Endpoint<ModifyParkingCarNumberRequest, ModifyParkingCarNumberResponse> MODIFY_PARKING_FEE_WAVE_CAR_NUMBER = new Endpoint<>("modify_parking_fee_wave_car_number", ModifyParkingCarNumberRequest.class, ModifyParkingCarNumberResponse.class, true, "/evcs/v1/modify_parking_fee_wave_car_number");
    public static final Endpoint<QueryGroundLockAuthRequest, QueryGroundLockAuthResponse> QUERY_GROUND_LOCK_AUTH = new Endpoint<>("query_ground_lock_auth", QueryGroundLockAuthRequest.class, QueryGroundLockAuthResponse.class, true, "/evcs/sdk/query_ground_lock_auth");
    public static final Endpoint<NotificationUserOrderInfoRequest, NotificationUserOrderInfoResponse> NOTIFICATION_USER_ORDER_INFO = new Endpoint<>("notification_user_order_info", NotificationUserOrderInfoRequest.class, NotificationUserOrderInfoResponse.class, true, "/notification_user_order_info");
    public static final Endpoint<QueryUserOrderRequest, QueryUserOrderResponse> QUERY_USER_ORDER = new Endpoint<>("query_user_order", QueryUserOrderRequest.class, QueryUserOrderResponse.class, true, "/evcs/v1/query_user_order");
    public static final Endpoint<QueryOrderDetailLinkRequest, QueryOrderDetailLinkResponse> QUERY_ORDER_DETAIL_LINK = new Endpoint<>("query_order_detail_link", QueryOrderDetailLinkRequest.class, QueryOrderDetailLinkResponse.class, true, "/evcs/v1/query_order_detail_link");
    public static final Endpoint<QueryDropLockRequest, QueryDropLockResponse> QUERY_DROP_LOCK = new Endpoint<>("query_drop_lock", QueryDropLockRequest.class, QueryDropLockResponse.class, true, "/evcs/sdk/query_drop_lock");
    public static final Endpoint<QueryDropLockResultRequest, QueryDropLockResultResponse> QUERY_DROP_LOCK_RESULT = new Endpoint<>("query_drop_lock_result", QueryDropLockResultRequest.class, QueryDropLockResultResponse.class, true, "/evcs/sdk/query_drop_lock_result");

    public static List<Endpoint<?, ?>> standard() { return List.of(QUERY_TOKEN, QUERY_STATIONS_INFO, NOTIFICATION_STATION_STATUS, QUERY_STATION_STATUS, QUERY_STATION_STATS, QUERY_EQUIP_AUTH, QUERY_EQUIP_BUSINESS_POLICY, QUERY_START_CHARGE, NOTIFICATION_START_CHARGE_RESULT, QUERY_EQUIP_CHARGE_STATUS, NOTIFICATION_EQUIP_CHARGE_STATUS, QUERY_STOP_CHARGE, NOTIFICATION_STOP_CHARGE_RESULT, NOTIFICATION_CHARGE_ORDER_INFO, CHECK_CHARGE_ORDERS); }
    public static List<Endpoint<?, ?>> extensions() { return List.of(QUERY_OPEN_LINK, QUERY_GROUND_LOCKS, QUERY_PARKING_FREE_INFO, QUERY_CONFIRM_LINK, NOTIFICATION_USER_AUTH, QUERY_PARKING_STATION, QUERY_PARKING_FREE_WAVE, MODIFY_PARKING_FEE_WAVE_CAR_NUMBER, QUERY_GROUND_LOCK_AUTH, NOTIFICATION_USER_ORDER_INFO, QUERY_USER_ORDER, QUERY_ORDER_DETAIL_LINK, QUERY_DROP_LOCK, QUERY_DROP_LOCK_RESULT); }
    public static List<Endpoint<?, ?>> all() {
        return java.util.stream.Stream.concat(standard().stream(), extensions().stream()).toList();
    }
}
